// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeBuddy
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodeBuddy.e8140313-05d8-4859-8feb-8eb6e0235bcf";
        public const string Name = "CodeBuddy";
        public const string Description = @"A Simple Visual Studio extension that integrates GPT-3 text-davinci-003 model. It is using the Complete mode with the default settings. Install, go to View > Other Windows > CodeBuddy. You may dock it next in the Solution Explorer section.";
        public const string Language = "en-US";
        public const string Version = "1.2.2";
        public const string Author = "Iulian Oana";
        public const string Tags = "";
    }
}
