// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeBuddyExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCodeBuddyExtensionPackageString = "ccde062b-8797-4fdb-a583-e5c4b30d781e";
        public static Guid guidCodeBuddyExtensionPackage = new Guid(guidCodeBuddyExtensionPackageString);

        public const string guidCodeBuddyExtensionPackageCmdSetString = "36617ba4-4e12-407d-bf77-1c48c660b238";
        public static Guid guidCodeBuddyExtensionPackageCmdSet = new Guid(guidCodeBuddyExtensionPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CodeBuddyCommandId = 0x0100;
    }
}